[package]
name = "versatiles_image"
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
exclude.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
fast_image_resize = { version = "5.2.2", features = ["image"] }
image.workspace = true
imageproc = { version = "0.25.0", default-features = false }
webp = "0.3.1"

versatiles_core.workspace = true

[dev-dependencies]
rstest.workspace = true
